import type { Property } from "~/types/property";

export const About: string = "Lorem, ipsum dolor sit amet consectetur adipisicing elit. Doloremque quod sed, odio fugiat voluptatibus quo totam atque ratione facere vero in quis tempora est velit, numquam excepturi, porro perferendis magni autem modi illo enim! Provident nesciunt nihil eligendi quam quis aliquid. Ad neque minima perspiciatis. Temporibus voluptatum iure perferendis hic aliquid. Sint commodi dicta architecto rem a, sequi dolore officiis tempora quos ipsam quidem, dolor porro facilis excepturi. Delectus alias ad a quia commodi sunt vero, accusamus molestiae deserunt similique exercitationem ab illo eligendi numquam nesciunt maxime nam minus voluptatem saepe, officia quasi dicta aliquid officiis. Molestiae, harum. Quisquam, rem."

export const navItems = [
  {
    name: "Landlords",
    href: "/",
  },
  {
    name: "About Us",
    href: "/",
  },
  {
    name: "Careers",
    href: "/",
  },
  {
    name: "Contact",
    href: "/",
  },
];

// mockData.ts

export const mockProperties: Property[] = [
  {
    id: 1,
    name: "2B N1 A - 29 Shoreditch Heights",
    location: "London, UK",
    overallRating: 9.5,
    reviewCount: 3,
    ratingPercentage: "95%",
    createdAt: "2020-05-12T10:00:00Z",
    reviews: [
      {
        id: 101,
        type: "host-to-guest",
        channel: "hostaway",
        status: "published",
        rating: null,
        publicReview: "Shane and family are wonderful! Would definitely host again :)",
        categories: [
          { category: "cleanliness", rating: 10 },
          { category: "communication", rating: 10 },
          { category: "respect_house_rules", rating: 10 },
        ],
        submittedAt: "2020-08-21T22:45:14Z",
        guestName: "Shane Finkelstein",
        listingId: 1,
      },
      {
        id: 102,
        type: "guest-to-host",
        channel: "google",
        status: "published",
        rating: 9,
        publicReview: "Lovely flat, close to everything. A bit noisy at night though.",
        categories: [
          { category: "cleanliness", rating: 9 },
          { category: "communication", rating: 10 },
          { category: "location", rating: 8 },
        ],
        submittedAt: "2020-08-25T14:10:00Z",
        guestName: "Emily Carter",
        listingId: 1,
      },
      {
        id: 103,
        type: "guest-to-host",
        channel: "airbnb",
        status: "published",
        rating: 10,
        publicReview: "Amazing host, super responsive. The flat was spotless.",
        categories: [
          { category: "cleanliness", rating: 10 },
          { category: "communication", rating: 10 },
        ],
        submittedAt: "2020-09-01T09:30:00Z",
        guestName: "Liam Johnson",
        listingId: 1,
      },
    ],
  },
  {
    id: 2,
    name: "Seaside Villa Retreat",
    location: "Malaga, Spain",
    overallRating: 8.7,
    reviewCount: 4,
    ratingPercentage: "87%",
    createdAt: "2021-03-10T12:00:00Z",
    reviews: [
      {
        id: 201,
        type: "guest-to-host",
        channel: "hostaway",
        status: "published",
        rating: 8,
        publicReview: "The villa was beautiful, but Wi-Fi was unreliable.",
        categories: [
          { category: "cleanliness", rating: 9 },
          { category: "communication", rating: 7 },
          { category: "location", rating: 9 },
        ],
        submittedAt: "2021-04-05T18:15:00Z",
        guestName: "Carlos Rivera",
        listingId: 2,
      },
      {
        id: 202,
        type: "host-to-guest",
        channel: "hostaway",
        status: "published",
        rating: null,
        publicReview: "Carlos left the place tidy, great guest!",
        categories: [],
        submittedAt: "2021-04-06T11:00:00Z",
        guestName: "Carlos Rivera",
        listingId: 2,
      },
      {
        id: 203,
        type: "guest-to-host",
        channel: "google",
        status: "published",
        rating: 9,
        publicReview: "We had a fantastic family holiday, very spacious and clean.",
        categories: [
          { category: "cleanliness", rating: 9 },
          { category: "communication", rating: 9 },
        ],
        submittedAt: "2021-05-01T15:40:00Z",
        guestName: "Sofia Martinez",
        listingId: 2,
      },
      {
        id: 204,
        type: "guest-to-host",
        channel: "airbnb",
        status: "published",
        rating: 9,
        publicReview: "Beautiful sunsets from the terrace. Highly recommend.",
        categories: [
          { category: "location", rating: 10 },
          { category: "cleanliness", rating: 8 },
        ],
        submittedAt: "2021-05-10T20:00:00Z",
        guestName: "James Lee",
        listingId: 2,
      },
    ],
  },
  {
    id: 3,
    name: "Downtown Loft Apartment",
    location: "New York, USA",
    overallRating: 7.8,
    reviewCount: 3,
    ratingPercentage: "78%",
    createdAt: "2022-01-15T08:00:00Z",
    reviews: [
      {
        id: 301,
        type: "guest-to-host",
        channel: "google",
        status: "published",
        rating: 7,
        publicReview: "Nice loft, but could use better soundproofing.",
        categories: [
          { category: "cleanliness", rating: 8 },
          { category: "communication", rating: 7 },
          { category: "location", rating: 7 },
        ],
        submittedAt: "2022-02-10T10:30:00Z",
        guestName: "Olivia Green",
        listingId: 3,
      },
      {
        id: 302,
        type: "guest-to-host",
        channel: "airbnb",
        status: "published",
        rating: 8,
        publicReview: "Great location, stylish interior. Would book again.",
        categories: [
          { category: "cleanliness", rating: 8 },
          { category: "communication", rating: 8 },
        ],
        submittedAt: "2022-02-15T12:00:00Z",
        guestName: "Ethan Brown",
        listingId: 3,
      },
      {
        id: 303,
        type: "host-to-guest",
        channel: "hostaway",
        status: "published",
        rating: null,
        publicReview: "Ethan was polite and left the apartment in great condition.",
        categories: [],
        submittedAt: "2022-02-16T09:00:00Z",
        guestName: "Ethan Brown",
        listingId: 3,
      },
    ],
  },
];
